# Generated by Django 4.2.20 on 2025-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["room", "date", "start_time", "end_time"],
                name="bookings_bo_room_id_23b661_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "date", "start_time", "end_time"],
                name="bookings_bo_user_id_e6d3ff_idx",
            ),
        ),
    ]
