# Generated by Django 4.2.20 on 2025-04-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_bookings_bo_room_id_23b661_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
    ]
